default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

development:
  <<: *default
  database: "codhab_development"
  username: "<%= ENV['db_user'] %>"
  password: "<%= ENV['db_password'] %>"
  host: "<%= ENV['db_host'] %>"


#production:
  #<<: *default
  #database: codhab_production
  #username: postgres
  #password: codhab072771472
  #host: 10.233.38.16

test:
  <<: *default
  database: codhab_test
  username: "<%= ENV['db_user'] %>"
  password: "<%= ENV['db_password'] %>"
  host: "<%= ENV['db_host'] %>"
